---
- name: Copy script to remote host
  copy:
     src: laravel.sh
     dest: /tmp/laravel.sh
     mode: 0755

- name: Execute deployment script
  command: /tmp/laravel.sh

- name: Restart Apache
  service:
     name: apache2
     state: restarted
